dir: '{{.InterfaceDir}}'
structname: '{{.InterfaceName}}Mock'
filename: "{{.InterfaceName | lower}}_test.go"
pkgname: '{{.SrcPackageName}}_test'
template: testify
template-data:
  unroll-variadic: true
packages:
  github.com/mbretter/go-mongodb/v2:
    interfaces:
      Connector:
