quiet: False
disable-version-string: True
with-expecter: True
mockname: "{{.InterfaceName}}Mock"
filename: "{{.InterfaceNameLower}}_test.go"
outpkg: "{{.PackageName}}_test"
dir: "{{.InterfaceDir}}"
inpackage: False
packages:
  github.com/mbretter/go-mongodb:
    interfaces:
      Connector:
